const express = require('express');
const router = express.Router();
const refresh = require('../jobs/refresh');
const scheduler = require('../jobs/scheduler');
const newsService = require('../services/newsService');
const db = require('../db/database');

// Bearer ADMIN_TOKEN (Fly secret). Without the secret set, admin endpoints are disabled.
const requireAdmin = (req, res, next) => {
  const token = process.env.ADMIN_TOKEN;
  const given = (req.get('authorization') || '').replace(/^Bearer\s+/i, '') || req.get('x-admin-token');
  if (!token) return res.status(503).json({ success: false, error: 'ADMIN_TOKEN not configured' });
  if (given !== token) return res.status(401).json({ success: false, error: 'Unauthorized' });
  return next();
};

// GET /api/admin/jobs — public: schedule + last run per job (no secrets).
router.get('/jobs', (req, res) => {
  res.json({ success: true, data: scheduler.describe(), timestamp: new Date().toISOString() });
});

// POST /api/admin/jobs/:job/run — manual trigger. ?wait=1 blocks until the job finishes.
router.post('/jobs/:job/run', requireAdmin, async (req, res) => {
  const entry = scheduler.SCHEDULE.find((s) => s.job === req.params.job);
  if (!entry) return res.status(404).json({ success: false, error: `Unknown job. Jobs: ${scheduler.SCHEDULE.map((s) => s.job).join(', ')}` });
  if (refresh.status[entry.job]?.running) return res.status(409).json({ success: false, error: 'Job already running' });
  const job = entry.run();
  if (req.query.wait) return res.json({ success: true, data: await job });
  job.catch(() => {});
  return res.status(202).json({ success: true, data: { job: entry.job, started: true } });
});

// Prediction artifacts are generated by the Python feature pipeline.  Node only
// stores/serves them, avoiding a second implementation of model features.
router.post('/predictions', requireAdmin, async (req, res) => {
  try {
    const artifact = req.body;
    if (!artifact || !/^v2\./.test(artifact.model_version || '') || !Array.isArray(artifact.predictions)) {
      return res.status(400).json({ success: false, error: 'Expected v2 prediction artifact with predictions[]' });
    }
    await db.saveDataset('model_predictions_current', artifact, { model_version: artifact.model_version, generated_at: artifact.generated_at, games: artifact.predictions.length });
    return res.json({ success: true, data: { model_version: artifact.model_version, games: artifact.predictions.length } });
  } catch (error) { return res.status(500).json({ success: false, error: error.message }); }
});

// GET /admin/llm (also available as /api/admin/llm) — provider accounting and latest observed limits.
router.get('/llm', requireAdmin, async (req, res) => {
  try {
    const rows = await newsService.usage(7);
    const today = new Intl.DateTimeFormat('en-CA', { timeZone: 'America/New_York' }).format(new Date());
    const latest = Object.values(rows.reduce((acc, row) => {
      if (!acc[row.provider] || acc[row.provider].updated_at < row.updated_at) acc[row.provider] = row;
      return acc;
    }, {}));
    res.json({ success: true, data: { today: rows.filter((r) => r.day === today), last_7_days: rows, latest_limits: latest.map((r) => ({ provider: r.provider, remaining_requests: r.remaining_requests, remaining_tokens: r.remaining_tokens, reset_requests: r.reset_requests, reset_tokens: r.reset_tokens, updated_at: r.updated_at })), links: { groq: 'https://console.groq.com/settings/limits', openrouter: 'https://openrouter.ai/activity' } }, timestamp: new Date().toISOString() });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

module.exports = router;
