const db = require('../db/database');
const { getScoreboard, getUpcomingScoreboard } = require('./sportsDataService');
const { loadSeason, phi } = require('./playoffService');
const { getPlayedGames, getTeamStats } = require('./teamStatsService');
const { getPreview } = require('./previewService');
const weatherService = require('./weatherService');
const { getMicroMatchups, matchupAdjustment } = require('./microMatchupService');
const { currentSeason } = require('./rosterService');

// AFI Picks — our own model pick per game (spread, total, moneyline). For entertainment only.
//
// Margin model: team rating = points margin per game this season, blended with half of last season's
//   margin/game as a 4-game prior; home field +1.5 (0 at neutral sites).
// Adjustments: starting QB out (backup starts) -4 pts; each other injured starter listed Out -0.5 (max -2).
// Total model: expected points = average of team's scoring and opponent's points allowed per game, shrunk
//   toward the league average with a 4-game prior; weather flags (wind/rain/snow) -3.
// Win probability = Normal CDF(margin / 13.5). Picks are re-made hourly and lock at kickoff; graded vs the
//   ESPN (DraftKings) line we picked against.

const HOME_FIELD = 1.5;
const SD = 13.5;
const PRIOR_GAMES = 4;
const DISCLAIMER = 'AFI Picks are generated by a simple statistical model for entertainment only. Not betting advice.';

const round1 = (v) => Math.round(v * 10) / 10;
const half = (v) => Math.round(v * 2) / 2;
const fmtLine = (v) => (v > 0 ? `+${v}` : v === 0 ? 'PK' : `${v}`);
const implied = (ml) => (ml == null ? null : ml < 0 ? -ml / (-ml + 100) : 100 / (ml + 100));
const predictionArtifact = async () => {
  const row = await db.loadDataset('model_predictions_current');
  if (!row || !row.data?.generated_at || Date.now() - Date.parse(row.data.generated_at) > 48 * 3600e3) return null;
  return row.data;
};

const priorMargins = async (season) => {
  const played = await getPlayedGames();
  const sum = {}; const n = {};
  (played || []).filter((g) => g.season === season - 1 && g.game_type === 'REG').forEach((g) => {
    const m = g.home_score - g.away_score;
    sum[g.home] = (sum[g.home] || 0) + m; n[g.home] = (n[g.home] || 0) + 1;
    sum[g.away] = (sum[g.away] || 0) - m; n[g.away] = (n[g.away] || 0) + 1;
  });
  return Object.fromEntries(Object.keys(sum).map((t) => [t, (0.5 * sum[t]) / n[t]]));
};

const avg = (values) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0;
const teamMargin = (game, teamId) => game.home === teamId ? game.home_score - game.away_score : game.away_score - game.home_score;

// 45% last three, 30% games 4–7, 15% games 8+, and 10% of the prior
// season's final four. The early-season fallback deliberately uses the whole
// current sample and the same prior instead of pretending tiny samples are stable.
const weightedRecency = (teamId, abbreviation, data, played) => {
  const current = data.games.filter((g) => g.result && (g.home === teamId || g.away === teamId))
    .sort((a, b) => b.date.localeCompare(a.date)).map((g) => teamMargin(g, teamId));
  const prior = (played || []).filter((g) => g.season === data.season - 1 && g.game_type === 'REG' && (g.home === abbreviation || g.away === abbreviation))
    .sort((a, b) => b.date.localeCompare(a.date)).slice(0, 4)
    .map((g) => g.home === abbreviation ? g.home_score - g.away_score : g.away_score - g.home_score);
  if (current.length < 3) return { value: 0.75 * avg(current) + 0.25 * avg(prior), games: current.length, fallback: true };
  return {
    value: 0.45 * avg(current.slice(0, 3)) + 0.30 * avg(current.slice(3, 7)) + 0.15 * avg(current.slice(7)) + 0.10 * avg(prior),
    games: current.length, fallback: false
  };
};

const efficiency = (stats, abbreviation) => {
  const s = stats?.teams?.[abbreviation];
  if (!s) return { rating: 0, sample: 0, snippet: 'Efficiency data will populate after the next PBP refresh.' };
  const off = s.offense || {}; const def = s.defense || {};
  const ypp = (off.yards_per_play || 0) - (def.yards_per_play || 0);
  const turnover = (s.turnover_margin || 0) / Math.max(s.games || 1, 1);
  const third = (off.third_down_pct || 0) - (def.third_down_pct || 0);
  const redZone = (off.red_zone_td_pct || 0) - (def.red_zone_td_pct || 0);
  // YPP uses the documented 0.08 points-per-YPP conversion; the remaining
  // components normalize per-game turnovers and percentage-point rates.
  const rating = (ypp * 0.08) + (turnover * 1.4) + (third * 0.08) + (redZone * 0.05);
  return { rating, sample: s.games || 0, ypp, turnover, third, redZone, snippet: `${abbreviation} ${ypp >= 0 ? '+' : ''}${round1(ypp)} YPP differential · ${turnover >= 0 ? '+' : ''}${round1(turnover)} turnovers/game` };
};

const momentum = (abbreviation, season, played) => {
  const games = (played || []).filter((g) => g.season === season && g.game_type === 'REG' && (g.home === abbreviation || g.away === abbreviation))
    .sort((a, b) => b.date.localeCompare(a.date));
  let wins = 0; let covers = 0; let blowouts = 0; let upset = 0;
  games.forEach((g, index) => {
    const home = g.home === abbreviation; const pf = home ? g.home_score : g.away_score; const pa = home ? g.away_score : g.home_score;
    const won = pf > pa;
    if (won && index === wins) wins += 1;
    const line = home ? g.spread_line : (g.spread_line == null ? null : -g.spread_line);
    if (line != null && pf + line > pa && index === covers) covers += 1;
    if (pf - pa <= -14 && index === blowouts) blowouts += 1;
    if (index < 2 && won && line != null && line >= 7) upset += Math.abs(pf - pa);
  });
  const score = Math.max(-5, Math.min(5, (covers * 1.5) + wins + (upset ? 2 : 0) - (blowouts * 1.5)));
  return { score, adjustment: Math.max(-3, Math.min(3, score * 0.75)), label: score >= 2 ? 'Hot' : score <= -2 ? 'Cold' : 'Neutral', badge: score >= 2 ? '🔥' : score <= -2 ? '❄️' : '–' };
};

const buildModel = async (season) => {
  const data = await loadSeason(season);
  const prior = await priorMargins(season);
  const [played, stats] = await Promise.all([getPlayedGames(), getTeamStats(season)]);
  const byId = Object.fromEntries(data.teams.map((t) => [t.id, t]));
  const acc = {};
  let lgPts = 0; let lgN = 0;
  data.games.filter((g) => g.result && g.home_score != null).forEach((g) => {
    [[g.home, g.home_score, g.away_score], [g.away, g.away_score, g.home_score]].forEach(([id, pf, pa]) => {
      const a = acc[id] || (acc[id] = { pf: 0, pa: 0, g: 0 });
      a.pf += pf; a.pa += pa; a.g += 1;
      lgPts += pf; lgN += 1;
    });
  });
  const lg = lgN ? lgPts / lgN : 22;
  const teams = {};
  data.teams.forEach((t) => {
    const a = acc[t.id] || { pf: 0, pa: 0, g: 0 };
    const p = prior[t.abbreviation] || 0;
    const recency = weightedRecency(t.id, t.abbreviation, data, played);
    teams[t.id] = {
      rating: (a.pf - a.pa + p * PRIOR_GAMES) / (a.g + PRIOR_GAMES),
      off: (a.pf + lg * PRIOR_GAMES) / (a.g + PRIOR_GAMES),
      def: (a.pa + lg * PRIOR_GAMES) / (a.g + PRIOR_GAMES),
      games: a.g,
      recency,
      efficiency: efficiency(stats, t.abbreviation),
      momentum: momentum(t.abbreviation, season, played)
    };
  });
  return { season, teams, byId, league_ppg: lg };
};

const injuryAdjust = (side) => {
  if (!side) return { pts: 0, notes: [] };
  let pts = 0;
  const notes = [];
  if (side.starting_qb?.replaces) {
    pts -= 4;
    notes.push(`${side.abbreviation} starts ${side.starting_qb.name} with ${side.starting_qb.replaces.name} ${String(side.starting_qb.replaces.injury?.status || 'out').toLowerCase()}`);
  }
  const outStarters = (side.key_injuries || []).filter((i) => i.starter && ['Out', 'Injured Reserve'].includes(i.status) && i.position !== 'QB');
  const extra = Math.min(2, outStarters.length * 0.5);
  if (extra) {
    pts -= extra;
    notes.push(`${side.abbreviation} is without ${outStarters.length} starter${outStarters.length > 1 ? 's' : ''} (${outStarters.slice(0, 2).map((i) => i.name).join(', ')}${outStarters.length > 2 ? '…' : ''})`);
  }
  return { pts, notes };
};

const makePick = async (g, model) => {
  const h = model.teams[g.home.id];
  const a = model.teams[g.away.id];
  if (!h || !a) return null;
  const [preview, wx] = await Promise.all([getPreview(g.game_id).catch(() => null), weatherService.gameWeather(g).catch(() => null)]);
  const microMatchups = await getMicroMatchups({ season: model.season || currentSeason(), home: g.home.abbreviation, away: g.away.abbreviation, weather: wx, preview }).catch(() => []);
  const injH = injuryAdjust(preview?.home);
  const injA = injuryAdjust(preview?.away);
  const hfa = g.neutral_site ? 0 : HOME_FIELD;
  const recencyMargin = h.recency.value - a.recency.value;
  const efficiencyMargin = h.efficiency.rating - a.efficiency.rating;
  const momentumMargin = h.momentum.adjustment - a.momentum.adjustment;
  // The prediction is intentionally decomposed so every card can show why it differs from the market.
  const baseMargin = (recencyMargin * 0.60) + (efficiencyMargin * 0.30) + (momentumMargin * 0.10) + hfa + injH.pts - injA.pts;
  // Each matchup impact is explicitly team-relative; fold it into the line so
  // “adds/subtracts” in the card is a real AFI-line adjustment, not decoration.
  // The sum is capped (±2) until the signals have been backtested.
  const matchup = matchupAdjustment(microMatchups, g.home.abbreviation, g.away.abbreviation);
  const matchupMargin = matchup.capped;
  const margin = baseMargin + matchupMargin;
  const weatherAdj = wx?.impact?.totals_lean === 'under' ? -3 : 0;
  const homePts = (h.off + a.def) / 2 + (injH.pts - injA.pts) / 2;
  const awayPts = (a.off + h.def) / 2 - (injH.pts - injA.pts) / 2;
  const total = homePts + awayPts + weatherAdj;
  const pHome = phi(margin / SD);
  const L = g.lines || {};
  const home = g.home.abbreviation;
  const away = g.away.abbreviation;

  const pick = {
    game_id: g.game_id, week: g.week, date: g.date, home, away, home_id: g.home.id, away_id: g.away.id,
    model: { home_margin: round1(margin), spread_home: half(-margin), total: round1(total), home_win_prob: Math.round(pHome * 1000) / 10 },
    market: { spread_home: L.spread_home ?? null, total: L.total ?? null, moneyline_home: L.moneyline_home ?? null, moneyline_away: L.moneyline_away ?? null, provider: L.provider || null, details: L.details || null },
    weather: wx?.impact ? { level: wx.impact.level, note: wx.impact.note } : null,
    micro_matchups: microMatchups,
    micro_matchup_version: 11,
    matchup_adjustment: round1(matchupMargin),
    matchup_adjustment_uncapped: matchup.raw,
    weighted_recency: { home: round1(h.recency.value), away: round1(a.recency.value), home_games: h.recency.games, away_games: a.recency.games, fallback: h.recency.fallback || a.recency.fallback },
    efficiency_rating: { home: round1(h.efficiency.rating), away: round1(a.efficiency.rating), differential: round1(efficiencyMargin), home_sample: h.efficiency.sample, away_sample: a.efficiency.sample, snippet: `${h.efficiency.snippet}; ${a.efficiency.snippet}` },
    momentum: { home: h.momentum, away: a.momentum, differential: round1(momentumMargin) },
    made_at: new Date().toISOString()
  };

  const why = [];
  const fav = margin >= 0 ? home : away;
  why.push(`Our model makes ${fav} a ${Math.abs(half(margin)) || 'pick-em'}${Math.abs(half(margin)) ? '-point favorite' : ''}${L.spread_home != null ? ` (market: ${home} ${fmtLine(L.spread_home)})` : ''}, with ${margin >= 0 ? home : away} winning ${Math.round((margin >= 0 ? pHome : 1 - pHome) * 100)}% of the time.`);

  if (L.spread_home != null) {
    const edge = margin + L.spread_home; // > 0: home covers
    const side = edge >= 0 ? 'home' : 'away';
    pick.spread = { side, team: side === 'home' ? home : away, line: side === 'home' ? L.spread_home : -L.spread_home, edge: round1(Math.abs(edge)), confidence: Math.abs(edge) >= 3 ? 'high' : Math.abs(edge) >= 1.5 ? 'medium' : 'low' };
  }
  const marketMargin = L.spread_home == null ? null : -L.spread_home;
  const confidenceEdge = marketMargin == null ? 0 : Math.abs(margin - marketMargin);
  pick.confidence_stars = confidenceEdge >= 7 ? 5 : confidenceEdge >= 5 ? 4 : confidenceEdge >= 3 ? 3 : confidenceEdge >= 1.5 ? 2 : 1;
  pick.confidence_edge = round1(confidenceEdge);
  if (L.total != null) {
    const edge = total - L.total;
    pick.total = { side: edge >= 0 ? 'over' : 'under', line: L.total, edge: round1(Math.abs(edge)), confidence: Math.abs(edge) >= 4 ? 'high' : Math.abs(edge) >= 2 ? 'medium' : 'low' };
  }
  const side = pHome >= 0.5 ? 'home' : 'away';
  const ml = side === 'home' ? L.moneyline_home : L.moneyline_away;
  const imp = implied(ml);
  pick.moneyline = { side, team: side === 'home' ? home : away, odds: ml ?? null, model_prob: Math.round((side === 'home' ? pHome : 1 - pHome) * 1000) / 10, implied_prob: imp == null ? null : Math.round(imp * 1000) / 10 };

  if (pick.spread) why.push(`The ${pick.confidence_stars}-star edge is driven by a ${round1(recencyMargin)}-point recency differential, ${round1(efficiencyMargin)} from efficiency, and ${round1(momentumMargin)} from momentum; it favors ${pick.spread.team} ${fmtLine(pick.spread.line)}${pick.total ? `, with ${pick.total.side.toUpperCase()} ${pick.total.line} on the total` : ''}.`);
  const notes = [...injA.notes, ...injH.notes];
  if (microMatchups.length) why.push(`Key matchup: ${microMatchups[0].text}`);
  if (notes.length) why.push(`Injuries factored in: ${notes.join('; ')}.`);
  if (weatherAdj) why.push(`Weather: ${wx.impact.flags.map((f) => f.label).join(', ')} trims 3 points from our total.`);
  pick.reasoning = why.slice(0, 4).join(' ');
  // Lazy require avoids the model/picks service dependency during model builds.
  pick.model_v2 = require('./modelService').explainPick(pick);
  return pick;
};

const applyPythonPrediction = (pick, prediction) => {
  if (!prediction) { pick.model_version = 'v1 (fallback)'; return pick; }
  const margin = Number(prediction.home_margin); const pHome = Number(prediction.home_win_probability);
  if (!Number.isFinite(margin) || !Number.isFinite(pHome)) { pick.model_version = 'v1 (fallback)'; return pick; }
  pick.model = { ...pick.model, home_margin: round1(margin), spread_home: half(-margin), home_win_prob: Math.round(pHome * 1000) / 10 };
  pick.model_version = prediction.model_version;
  pick.features = prediction.features;
  pick.model_v2 = { version: prediction.model_version, contributions: prediction.contributions || [] };
  const L = pick.market;
  if (L.spread_home != null) {
    const edge = margin + L.spread_home; const side = edge >= 0 ? 'home' : 'away';
    pick.spread = { side, team: side === 'home' ? pick.home : pick.away, line: side === 'home' ? L.spread_home : -L.spread_home, edge: round1(Math.abs(edge)), confidence: Math.abs(edge) >= 3 ? 'high' : Math.abs(edge) >= 1.5 ? 'medium' : 'low' };
    const confidenceEdge = Math.abs(margin + L.spread_home);
    pick.confidence_stars = confidenceEdge >= 7 ? 5 : confidenceEdge >= 5 ? 4 : confidenceEdge >= 3 ? 3 : confidenceEdge >= 1.5 ? 2 : 1;
  }
  const side = pHome >= .5 ? 'home' : 'away'; const ml = side === 'home' ? L.moneyline_home : L.moneyline_away;
  pick.moneyline = { ...pick.moneyline, side, team: side === 'home' ? pick.home : pick.away, odds: ml ?? null, model_prob: Math.round((side === 'home' ? pHome : 1 - pHome) * 1000) / 10, implied_prob: implied(ml) == null ? null : Math.round(implied(ml) * 1000) / 10 };
  return pick;
};

// --- Storage, locking and grading ------------------------------------------------------

const key = (season) => `afi_picks_${season}`;
const load = async (season) => (await db.loadDataset(key(season)))?.data || { season, picks: {} };

const grade = (p, g) => {
  const hs = g.home.score; const as = g.away.score;
  const out = {};
  if (p.spread) {
    const homeCover = hs - as + p.market.spread_home;
    const res = homeCover === 0 ? 'P' : (homeCover > 0) === (p.spread.side === 'home') ? 'W' : 'L';
    out.spread = res;
  }
  if (p.total) {
    const t = hs + as;
    out.total = t === p.total.line ? 'P' : (t > p.total.line) === (p.total.side === 'over') ? 'W' : 'L';
  }
  out.moneyline = hs === as ? 'P' : (hs > as) === (p.moneyline.side === 'home') ? 'W' : 'L';
  return { ...out, final: `${p.away} ${as} @ ${p.home} ${hs}` };
};

const record = (picks) => {
  const r = { spread: { w: 0, l: 0, p: 0 }, total: { w: 0, l: 0, p: 0 }, moneyline: { w: 0, l: 0, p: 0 } };
  picks.filter((p) => p.result).forEach((p) => {
    ['spread', 'total', 'moneyline'].forEach((k) => {
      const v = p.result[k];
      if (v === 'W') r[k].w += 1; else if (v === 'L') r[k].l += 1; else if (v === 'P') r[k].p += 1;
    });
  });
  Object.values(r).forEach((x) => { x.pct = x.w + x.l ? Math.round((1000 * x.w) / (x.w + x.l)) / 10 : null; x.text = `${x.w}-${x.l}${x.p ? `-${x.p}` : ''}`; });
  return r;
};

const segmentedRecord = (picks, key, value) => record(picks.filter((p) => key === 'stars' ? p.confidence_stars === value : [p.momentum?.home?.label, p.momentum?.away?.label].includes(value)));

// --- Historical re-run ----------------------------------------------------------
// The backtest uses only rows dated before each kickoff.  `schedules_played`
// supplies nflverse closing spread/total values and is never used as a feature
// for the game being graded.
const historicalTeam = (team, kickoff, games) => {
  const past = games.filter((g) => g.date < kickoff && (g.home === team || g.away === team));
  const margins = past.map((g) => g.home === team ? g.home_score - g.away_score : g.away_score - g.home_score);
  const pf = past.map((g) => g.home === team ? g.home_score : g.away_score);
  const pa = past.map((g) => g.home === team ? g.away_score : g.home_score);
  const recent = margins.slice(-3);
  const prior = games.filter((g) => g.season === 2025 && (g.home === team || g.away === team)).slice(-4)
    .map((g) => g.home === team ? g.home_score - g.away_score : g.away_score - g.home_score);
  const blend = (values, fallback) => values.length ? avg(values) : avg(fallback);
  return { margin: 0.75 * blend(recent, margins) + 0.25 * blend(prior, []), pf: blend(pf, []), pa: blend(pa, []), games: past.length };
};

const historicalRow = (g, allGames) => {
  const h = historicalTeam(g.home, g.date, allGames); const a = historicalTeam(g.away, g.date, allGames);
  const margin = round1((h.margin - a.margin) * 0.6 + ((h.pf - a.pa) - (a.pf - h.pa)) * 0.1 + 1.5);
  const modelHome = margin >= 0;
  const total = round1(((h.pf + a.pa) + (a.pf + h.pa)) / 2 || 44);
  // nflverse schedules use a positive spread_line when the home side lays
  // points (e.g. SEA 3 means SEA -3), unlike ESPN's signed home spread.
  const homeCover = g.home_score - g.away_score - (g.spread_line || 0);
  const su = (modelHome ? g.home_score > g.away_score : g.away_score > g.home_score) ? 'W' : 'L';
  const ats = g.spread_line == null ? null : (homeCover === 0 ? 'P' : ((homeCover > 0) === modelHome ? 'W' : 'L'));
  const ou = g.total_line == null ? null : (g.home_score + g.away_score === g.total_line ? 'P' : ((g.home_score + g.away_score > g.total_line) === (total > g.total_line) ? 'W' : 'L'));
  const favoriteHome = (g.spread_line || 0) > 0;
  const favorite = favoriteHome ? g.home : g.away;
  const favoriteSu = (favorite === g.home ? g.home_score > g.away_score : g.away_score > g.home_score) ? 'W' : 'L';
  const homeSu = g.home_score > g.away_score ? 'W' : 'L';
  const stars = Math.max(1, Math.min(5, Math.ceil(Math.abs(margin - (g.spread_line || 0)) / 1.5)));
  return { game_id: `${g.season}-${g.week}-${g.away}-${g.home}`, season: g.season, week: g.week, kickoff: g.date, away: g.away, home: g.home,
    model: { home_margin: margin, total, pick: modelHome ? g.home : g.away, stars, prior_games: { home: h.games, away: a.games } },
    closing_spread: g.spread_line, closing_total: g.total_line, home_score: g.home_score, away_score: g.away_score,
    results: { su, ats, ou, favorite_su: favoriteSu, home_su: homeSu } };
};

const pctRecord = (rows, field, wanted = 'W') => {
  const eligible = rows.filter((r) => r.results[field] != null);
  const wins = eligible.filter((r) => r.results[field] === wanted).length;
  return { wins, games: eligible.length, pct: eligible.length ? round1(wins * 100 / eligible.length) : null };
};

const shapeBacktest = (rows) => ({
  label: 'Backtest Weeks 1-3 (model re-run, not live picks)',
  weeks: [1, 2, 3].map((week) => { const games = rows.filter((r) => r.week === week); return { week, games: games.length, su: pctRecord(games, 'su'), ats: pctRecord(games, 'ats'), ou: pctRecord(games, 'ou') }; }),
  total: { games: rows.length, su: pctRecord(rows, 'su'), ats: pctRecord(rows, 'ats'), ou: pctRecord(rows, 'ou') },
  by_stars: [1, 2, 3, 4, 5].map((stars) => { const games = rows.filter((r) => r.model.stars === stars); return { stars, games: games.length, su: pctRecord(games, 'su'), ats: pctRecord(games, 'ats'), ou: pctRecord(games, 'ou') }; }),
  baselines: { always_favorite_su: pctRecord(rows, 'favorite_su'), always_home_su: pctRecord(rows, 'home_su') }, rows
});

const refreshBacktest = async () => {
  const played = await getPlayedGames();
  const games = (played || []).filter((g) => g.season === 2026 && g.game_type === 'REG' && g.week >= 1 && g.week <= 3 && g.home_score != null)
    .sort((a, b) => a.date.localeCompare(b.date));
  const history = (played || []).filter((g) => g.game_type === 'REG' && (g.season === 2025 || (g.season === 2026 && g.date < '2026-10-01')));
  const rows = games.map((g) => historicalRow(g, history));
  await Promise.all(rows.map((r) => db.run(`INSERT OR REPLACE INTO picks_backtest (game_id, season, week, kickoff, away, home, model_json, closing_spread, closing_total, home_score, away_score, results_json, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [r.game_id, r.season, r.week, r.kickoff, r.away, r.home, JSON.stringify(r.model), r.closing_spread, r.closing_total, r.home_score, r.away_score, JSON.stringify(r.results), new Date().toISOString()])));
  return shapeBacktest(rows);
};

// Weeks 1-3 are final, so the backtest only needs recomputing when the played
// games feed changes; cache it rather than re-running it (and 48 upserts) per request.
let backtestMemo = null;
const getBacktest = async () => {
  if (backtestMemo && Date.now() - backtestMemo.at < 6 * 3600e3) return backtestMemo.promise;
  const entry = { at: Date.now(), promise: refreshBacktest() };
  backtestMemo = entry;
  entry.promise.catch(() => { if (backtestMemo === entry) backtestMemo = null; });
  return entry.promise;
};

// Re-picks unstarted games, locks started ones (keeps the last pre-kickoff pick) and grades finals.
const refreshPicks = async ({ week = null } = {}) => {
  const season = currentSeason();
  const state = await load(season);
  const board = week ? await getScoreboard({ week, season, seasonType: 2 }) : await getUpcomingScoreboard();
  if (board.season_type !== 2 && !week) return { season, week: board.week, skipped: 'not regular season' };
  const model = await buildModel(season);
  const artifact = await predictionArtifact();
  const predicted = new Map((artifact?.predictions || []).flatMap((p) => [[p.game_id, p], [p.espn_id, p]].filter(([id]) => id)));
  let made = 0; let graded = 0;
  for (const g of board.games) {
    const existing = state.picks[g.game_id];
    if (g.status.state === 'pre') {
      const p = await makePick(g, model);
      if (p) { state.picks[g.game_id] = applyPythonPrediction(p, predicted.get(g.game_id)); made += 1; }
    } else if (existing && !existing.locked_at) {
      existing.locked_at = existing.locked_at || g.date;
    }
    if (existing && g.status.completed && !existing.result) {
      existing.result = grade(existing, g);
      graded += 1;
    }
  }
  state.updated_at = new Date().toISOString();
  await db.saveDataset(key(season), state, { picks: Object.keys(state.picks).length });
  return { season, week: board.week, made, graded };
};

const getPicks = async ({ week = null } = {}) => {
  const season = currentSeason();
  const board = week ? await getScoreboard({ week, season, seasonType: 2 }) : await getUpcomingScoreboard();
  let state = await load(season);
  // First visit for a week (or stale > 1h): compute now.
  const missing = board.games.some((g) => g.status.state === 'pre' && !state.picks[g.game_id]);
  // Recalculate pre-kickoff legacy picks once after a model schema upgrade so
  // clients never receive a mix of old and new pick-card fields.
  const outdated = board.games.some((g) => {
    const pick = state.picks[g.game_id];
    return g.status.state === 'pre' && pick && (pick.confidence_stars == null || pick.micro_matchup_version !== 11
      || (pick.micro_matchups || []).some((m) => ['Surface', 'Weather'].includes(m.label) || !m.sample || !/\d/.test(m.text || '')));
  });
  if (missing || outdated || !state.updated_at || Date.now() - Date.parse(state.updated_at) > 3600e3) {
    await refreshPicks({ week: board.week });
    state = await load(season);
  }
  const all = Object.values(state.picks);
  const games = board.games.map((g) => ({
    game_id: g.game_id, date: g.date, state: g.status.state, detail: g.status.detail,
    away: { id: g.away.id, abbreviation: g.away.abbreviation, name: g.away.name, logo: g.away.logo, score: g.away.score, record: g.away.record },
    home: { id: g.home.id, abbreviation: g.home.abbreviation, name: g.home.name, logo: g.home.logo, score: g.home.score, record: g.home.record },
    pick: state.picks[g.game_id] || null
  }));
  const byWeek = {};
  all.filter((p) => p.result).forEach((p) => { (byWeek[p.week] ||= []).push(p); });
  return {
    season, week: board.week, games,
    record: record(all),
    confidence_record: [1, 2, 3, 4, 5].map((stars) => ({ stars, ...segmentedRecord(all, 'stars', stars) })),
    momentum_record: ['Hot', 'Neutral', 'Cold'].map((state) => ({ state, ...segmentedRecord(all, 'momentum', state) })),
    weekly: Object.entries(byWeek).map(([w, ps]) => ({ week: Number(w), ...record(ps) })).sort((x, y) => y.week - x.week),
    tracking_since: all.length ? all.map((p) => p.made_at).sort()[0] : null,
    disclaimer: DISCLAIMER,
    method: 'Margin = 60% weighted recency (45% last 3 games, 30% games 4–7, 15% games 8+, 10% last season’s final four) + 30% efficiency power rating (YPP, turnovers, third down and red zone) + 10% momentum. Teams with fewer than three current-season games use a season-plus-prior fallback. Momentum is capped at ±3 points. Home field (+1.5) and injuries are then applied. AFI Confidence Rating compares the model margin to the market: 1★ under 1.5 points through 5★ at 7+ points.',
    last_updated: state.updated_at
    , backtest: await getBacktest()
  };
};

module.exports = { refreshPicks, getPicks, makePick, buildModel, refreshBacktest, DISCLAIMER };
