const db = require('../db/database');
const { getScoreboard, getUpcomingScoreboard } = require('./sportsDataService');
const { loadSeason, phi } = require('./playoffService');
const { getPlayedGames } = require('./teamStatsService');
const { getPreview } = require('./previewService');
const weatherService = require('./weatherService');
const { currentSeason } = require('./rosterService');

// AFI Picks — our own model pick per game (spread, total, moneyline). For entertainment only.
//
// Margin model: team rating = points margin per game this season, blended with half of last season's
//   margin/game as a 4-game prior; home field +1.5 (0 at neutral sites).
// Adjustments: starting QB out (backup starts) -4 pts; each other injured starter listed Out -0.5 (max -2).
// Total model: expected points = average of team's scoring and opponent's points allowed per game, shrunk
//   toward the league average with a 4-game prior; weather flags (wind/rain/snow) -3.
// Win probability = Normal CDF(margin / 13.5). Picks are re-made hourly and lock at kickoff; graded vs the
//   ESPN (DraftKings) line we picked against.

const HOME_FIELD = 1.5;
const SD = 13.5;
const PRIOR_GAMES = 4;
const DISCLAIMER = 'AFI Picks are generated by a simple statistical model for entertainment only. Not betting advice.';

const round1 = (v) => Math.round(v * 10) / 10;
const half = (v) => Math.round(v * 2) / 2;
const fmtLine = (v) => (v > 0 ? `+${v}` : v === 0 ? 'PK' : `${v}`);
const implied = (ml) => (ml == null ? null : ml < 0 ? -ml / (-ml + 100) : 100 / (ml + 100));

const priorMargins = async (season) => {
  const played = await getPlayedGames();
  const sum = {}; const n = {};
  (played || []).filter((g) => g.season === season - 1 && g.game_type === 'REG').forEach((g) => {
    const m = g.home_score - g.away_score;
    sum[g.home] = (sum[g.home] || 0) + m; n[g.home] = (n[g.home] || 0) + 1;
    sum[g.away] = (sum[g.away] || 0) - m; n[g.away] = (n[g.away] || 0) + 1;
  });
  return Object.fromEntries(Object.keys(sum).map((t) => [t, (0.5 * sum[t]) / n[t]]));
};

const buildModel = async (season) => {
  const data = await loadSeason(season);
  const prior = await priorMargins(season);
  const byId = Object.fromEntries(data.teams.map((t) => [t.id, t]));
  const acc = {};
  let lgPts = 0; let lgN = 0;
  data.games.filter((g) => g.result && g.home_score != null).forEach((g) => {
    [[g.home, g.home_score, g.away_score], [g.away, g.away_score, g.home_score]].forEach(([id, pf, pa]) => {
      const a = acc[id] || (acc[id] = { pf: 0, pa: 0, g: 0 });
      a.pf += pf; a.pa += pa; a.g += 1;
      lgPts += pf; lgN += 1;
    });
  });
  const lg = lgN ? lgPts / lgN : 22;
  const teams = {};
  data.teams.forEach((t) => {
    const a = acc[t.id] || { pf: 0, pa: 0, g: 0 };
    const p = prior[t.abbreviation] || 0;
    teams[t.id] = {
      rating: (a.pf - a.pa + p * PRIOR_GAMES) / (a.g + PRIOR_GAMES),
      off: (a.pf + lg * PRIOR_GAMES) / (a.g + PRIOR_GAMES),
      def: (a.pa + lg * PRIOR_GAMES) / (a.g + PRIOR_GAMES),
      games: a.g
    };
  });
  return { teams, byId, league_ppg: lg };
};

const injuryAdjust = (side) => {
  if (!side) return { pts: 0, notes: [] };
  let pts = 0;
  const notes = [];
  if (side.starting_qb?.replaces) {
    pts -= 4;
    notes.push(`${side.abbreviation} starts ${side.starting_qb.name} with ${side.starting_qb.replaces.name} ${String(side.starting_qb.replaces.injury?.status || 'out').toLowerCase()}`);
  }
  const outStarters = (side.key_injuries || []).filter((i) => i.starter && ['Out', 'Injured Reserve'].includes(i.status) && i.position !== 'QB');
  const extra = Math.min(2, outStarters.length * 0.5);
  if (extra) {
    pts -= extra;
    notes.push(`${side.abbreviation} is without ${outStarters.length} starter${outStarters.length > 1 ? 's' : ''} (${outStarters.slice(0, 2).map((i) => i.name).join(', ')}${outStarters.length > 2 ? '…' : ''})`);
  }
  return { pts, notes };
};

const makePick = async (g, model) => {
  const h = model.teams[g.home.id];
  const a = model.teams[g.away.id];
  if (!h || !a) return null;
  const [preview, wx] = await Promise.all([getPreview(g.game_id).catch(() => null), weatherService.gameWeather(g).catch(() => null)]);
  const injH = injuryAdjust(preview?.home);
  const injA = injuryAdjust(preview?.away);
  const hfa = g.neutral_site ? 0 : HOME_FIELD;
  const margin = h.rating - a.rating + hfa + injH.pts - injA.pts; // expected home margin
  const weatherAdj = wx?.impact?.totals_lean === 'under' ? -3 : 0;
  const homePts = (h.off + a.def) / 2 + (injH.pts - injA.pts) / 2;
  const awayPts = (a.off + h.def) / 2 - (injH.pts - injA.pts) / 2;
  const total = homePts + awayPts + weatherAdj;
  const pHome = phi(margin / SD);
  const L = g.lines || {};
  const home = g.home.abbreviation;
  const away = g.away.abbreviation;

  const pick = {
    game_id: g.game_id, week: g.week, date: g.date, home, away, home_id: g.home.id, away_id: g.away.id,
    model: { home_margin: round1(margin), spread_home: half(-margin), total: round1(total), home_win_prob: Math.round(pHome * 1000) / 10 },
    market: { spread_home: L.spread_home ?? null, total: L.total ?? null, moneyline_home: L.moneyline_home ?? null, moneyline_away: L.moneyline_away ?? null, provider: L.provider || null, details: L.details || null },
    weather: wx?.impact ? { level: wx.impact.level, note: wx.impact.note } : null,
    made_at: new Date().toISOString()
  };

  const why = [];
  const fav = margin >= 0 ? home : away;
  why.push(`Our model makes ${fav} a ${Math.abs(half(margin)) || 'pick-em'}${Math.abs(half(margin)) ? '-point favorite' : ''}${L.spread_home != null ? ` (market: ${home} ${fmtLine(L.spread_home)})` : ''}, with ${margin >= 0 ? home : away} winning ${Math.round((margin >= 0 ? pHome : 1 - pHome) * 100)}% of the time.`);

  if (L.spread_home != null) {
    const edge = margin + L.spread_home; // > 0: home covers
    const side = edge >= 0 ? 'home' : 'away';
    pick.spread = { side, team: side === 'home' ? home : away, line: side === 'home' ? L.spread_home : -L.spread_home, edge: round1(Math.abs(edge)), confidence: Math.abs(edge) >= 3 ? 'high' : Math.abs(edge) >= 1.5 ? 'medium' : 'low' };
  }
  if (L.total != null) {
    const edge = total - L.total;
    pick.total = { side: edge >= 0 ? 'over' : 'under', line: L.total, edge: round1(Math.abs(edge)), confidence: Math.abs(edge) >= 4 ? 'high' : Math.abs(edge) >= 2 ? 'medium' : 'low' };
  }
  const side = pHome >= 0.5 ? 'home' : 'away';
  const ml = side === 'home' ? L.moneyline_home : L.moneyline_away;
  const imp = implied(ml);
  pick.moneyline = { side, team: side === 'home' ? home : away, odds: ml ?? null, model_prob: Math.round((side === 'home' ? pHome : 1 - pHome) * 1000) / 10, implied_prob: imp == null ? null : Math.round(imp * 1000) / 10 };

  if (pick.spread) why.push(`That's ${pick.spread.edge} points of edge on ${pick.spread.team} ${fmtLine(pick.spread.line)}${pick.total ? `, and a model total of ${round1(total)} vs ${L.total} points to the ${pick.total.side.toUpperCase()}` : ''}.`);
  const notes = [...injA.notes, ...injH.notes];
  if (notes.length) why.push(`Injuries factored in: ${notes.join('; ')}.`);
  if (weatherAdj) why.push(`Weather: ${wx.impact.flags.map((f) => f.label).join(', ')} trims 3 points from our total.`);
  pick.reasoning = why.slice(0, 4).join(' ');
  return pick;
};

// --- Storage, locking and grading ------------------------------------------------------

const key = (season) => `afi_picks_${season}`;
const load = async (season) => (await db.loadDataset(key(season)))?.data || { season, picks: {} };

const grade = (p, g) => {
  const hs = g.home.score; const as = g.away.score;
  const out = {};
  if (p.spread) {
    const homeCover = hs - as + p.market.spread_home;
    const res = homeCover === 0 ? 'P' : (homeCover > 0) === (p.spread.side === 'home') ? 'W' : 'L';
    out.spread = res;
  }
  if (p.total) {
    const t = hs + as;
    out.total = t === p.total.line ? 'P' : (t > p.total.line) === (p.total.side === 'over') ? 'W' : 'L';
  }
  out.moneyline = hs === as ? 'P' : (hs > as) === (p.moneyline.side === 'home') ? 'W' : 'L';
  return { ...out, final: `${p.away} ${as} @ ${p.home} ${hs}` };
};

const record = (picks) => {
  const r = { spread: { w: 0, l: 0, p: 0 }, total: { w: 0, l: 0, p: 0 }, moneyline: { w: 0, l: 0, p: 0 } };
  picks.filter((p) => p.result).forEach((p) => {
    ['spread', 'total', 'moneyline'].forEach((k) => {
      const v = p.result[k];
      if (v === 'W') r[k].w += 1; else if (v === 'L') r[k].l += 1; else if (v === 'P') r[k].p += 1;
    });
  });
  Object.values(r).forEach((x) => { x.pct = x.w + x.l ? Math.round((1000 * x.w) / (x.w + x.l)) / 10 : null; x.text = `${x.w}-${x.l}${x.p ? `-${x.p}` : ''}`; });
  return r;
};

// Re-picks unstarted games, locks started ones (keeps the last pre-kickoff pick) and grades finals.
const refreshPicks = async ({ week = null } = {}) => {
  const season = currentSeason();
  const state = await load(season);
  const board = week ? await getScoreboard({ week, season, seasonType: 2 }) : await getUpcomingScoreboard();
  if (board.season_type !== 2 && !week) return { season, week: board.week, skipped: 'not regular season' };
  const model = await buildModel(season);
  let made = 0; let graded = 0;
  for (const g of board.games) {
    const existing = state.picks[g.game_id];
    if (g.status.state === 'pre') {
      const p = await makePick(g, model);
      if (p) { state.picks[g.game_id] = p; made += 1; }
    } else if (existing && !existing.locked_at) {
      existing.locked_at = existing.locked_at || g.date;
    }
    if (existing && g.status.completed && !existing.result) {
      existing.result = grade(existing, g);
      graded += 1;
    }
  }
  state.updated_at = new Date().toISOString();
  await db.saveDataset(key(season), state, { picks: Object.keys(state.picks).length });
  return { season, week: board.week, made, graded };
};

const getPicks = async ({ week = null } = {}) => {
  const season = currentSeason();
  const board = week ? await getScoreboard({ week, season, seasonType: 2 }) : await getUpcomingScoreboard();
  let state = await load(season);
  // First visit for a week (or stale > 1h): compute now.
  const missing = board.games.some((g) => g.status.state === 'pre' && !state.picks[g.game_id]);
  if (missing || !state.updated_at || Date.now() - Date.parse(state.updated_at) > 3600e3) {
    await refreshPicks({ week: board.week });
    state = await load(season);
  }
  const all = Object.values(state.picks);
  const games = board.games.map((g) => ({
    game_id: g.game_id, date: g.date, state: g.status.state, detail: g.status.detail,
    away: { id: g.away.id, abbreviation: g.away.abbreviation, name: g.away.name, logo: g.away.logo, score: g.away.score, record: g.away.record },
    home: { id: g.home.id, abbreviation: g.home.abbreviation, name: g.home.name, logo: g.home.logo, score: g.home.score, record: g.home.record },
    pick: state.picks[g.game_id] || null
  }));
  const byWeek = {};
  all.filter((p) => p.result).forEach((p) => { (byWeek[p.week] ||= []).push(p); });
  return {
    season, week: board.week, games,
    record: record(all),
    weekly: Object.entries(byWeek).map(([w, ps]) => ({ week: Number(w), ...record(ps) })).sort((x, y) => y.week - x.week),
    tracking_since: all.length ? all.map((p) => p.made_at).sort()[0] : null,
    disclaimer: DISCLAIMER,
    method: 'Margin = season point-margin rating (with half of last season as a 4-game prior) + 1.5 home field, adjusted for a starting QB out (-4) and injured starters (-0.5 each, max -2). Total = blended team scoring/allowed per game, -3 for wind/rain/snow. Win probability from a normal distribution (sd 13.5). Picks re-run hourly until kickoff, then lock; graded against the ESPN (DraftKings) line at pick time.',
    last_updated: state.updated_at
  };
};

module.exports = { refreshPicks, getPicks, makePick, buildModel, DISCLAIMER };
