import { Link, useParams, useSearchParams } from 'react-router-dom';
import { useApi } from '../api.js';
import { Loading, ErrorBox, Logo, Updated } from '../components.jsx';
import { SocialWidget } from './Social.jsx';

const ago = (iso) => {
  const m = Math.round((Date.now() - Date.parse(iso)) / 60000);
  if (m < 60) return `${Math.max(m, 1)}m ago`;
  if (m < 48 * 60) return `${Math.round(m / 60)}h ago`;
  return new Date(iso).toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
};

const AI_NOTE = 'Summary generated by AI from linked sources';

function StoryCard({ s }) {
  return (
    <Link to={`/news/${s.id}`} className="card story-card">
      <div className="story-meta">
        <span className={`story-type ${s.kind}`}>{s.type}</span>
        {s.teams.slice(0, 3).map((t) => <span key={t} className="tag">{t}</span>)}
        <span className="muted small grow-right">{ago(s.published)}</span>
      </div>
      <h3 className="story-title">{s.title}</h3>
      {s.excerpt && <p className="story-excerpt">{s.excerpt}</p>}
      <div className="muted small">
        {`${s.source_count} source${s.source_count === 1 ? '' : 's'}${s.ai ? ` · ${AI_NOTE}` : ' · Written from data'}`}
      </div>
    </Link>
  );
}

function Headlines({ items }) {
  if (!items.length) return null;
  return (
    <>
      <h2 className="section-title">More headlines <span className="muted small">(summary pending — links go to the original outlet)</span></h2>
      <div className="card list-card">
        {items.map((h) => (
          <div key={h.id} className="headline-row">
            <span className="grow">{h.title}</span>
            <span className="muted small">{h.sources.map((s, i) => <a key={s.url} href={s.url} target="_blank" rel="noreferrer">{i ? ', ' : ''}<u>{s.name}</u></a>)} · {ago(h.published)}</span>
          </div>
        ))}
      </div>
    </>
  );
}

export function NewsFeed({ team = null, compact = false }) {
  const [params, setParams] = useSearchParams();
  const kind = compact ? null : params.get('kind');
  const qs = new URLSearchParams();
  if (team) qs.set('team', team);
  if (kind) qs.set('kind', kind);
  const { data, error, loading } = useApi(`/news?${qs}`);
  if (loading) return <Loading label="Loading news…" />;
  if (error) return <ErrorBox error={error} />;
  const d = data.data;
  const setKind = (k) => { const next = new URLSearchParams(params); if (k) next.set('kind', k); else next.delete('kind'); setParams(next, { replace: true }); };
  return (
    <div>
      {!compact && (
        <div className="tabs">
          {[[null, 'All'], ['headline', 'News'], ['data', 'Data stories']].map(([k, label]) => (
            <button key={label} type="button" className={kind === k ? 'active' : ''} onClick={() => setKind(k)}>{label}</button>
          ))}
        </div>
      )}
      {!d.stories.length && <div className="state">No stories yet{team ? ' for this team' : ''}.</div>}
      {[['headline', 'Latest news'], ['data', 'From the data']].map(([k, label]) => {
        const list = d.stories.filter((s) => s.kind === k);
        if (!list.length) return null;
        return (
          <div key={k}>
            {!kind && <h2 className="section-title">{label}</h2>}
            <div className="grid story-grid">{list.map((s) => <StoryCard key={s.id} s={s} />)}</div>
          </div>
        );
      })}
      {kind !== 'data' && <Headlines items={d.headlines} />}
      <p className="muted small note">
        We don’t republish articles. News stories are short summaries written by AI from the headlines and snippets of public feeds
        (ESPN, CBS Sports, Yahoo Sports, ProFootballTalk), with links to every source. Data stories are generated from ESPN game, injury and transaction data.
      </p>
      <Updated at={d.last_updated} />
    </div>
  );
}

// Matchup preview block: latest readable stories tagging either team (both-team stories first).
export function MatchupNews({ away, home, limit = 6 }) {
  const { data, error, loading } = useApi(`/news?team=${away.abbreviation},${home.abbreviation}&limit=${limit}`);
  return (
    <div className="card">
      <h3 className="card-title">Matchup news · {away.abbreviation} &amp; {home.abbreviation}</h3>
      {loading && <p className="muted small">Loading news…</p>}
      {error && <p className="muted small">News unavailable: {error.message}</p>}
      {data && !data.data.stories.length && <p className="muted small">No stories for these teams yet.</p>}
      {data && data.data.stories.map((s) => (
        <Link key={s.id} to={`/news/${s.id}`} className="headline-row">
          <span className={`story-type ${s.kind}`}>{s.type}</span>
          <span className="grow"><b>{s.title}</b>{s.excerpt && <span className="muted small"> — {s.excerpt.length > 140 ? `${s.excerpt.slice(0, 140)}…` : s.excerpt}</span>}</span>
          <span className="muted small">{s.teams.filter((t) => t === away.abbreviation || t === home.abbreviation).join(' · ')} · {ago(s.published)}</span>
        </Link>
      ))}
      {data && data.data.stories.some((s) => s.ai) && <p className="muted small note">{AI_NOTE}. Data stories are written from ESPN data.</p>}
      <p className="small"><Link to={`/teams/${away.abbreviation}?tab=news`}><u>All {away.abbreviation} news</u></Link> · <Link to={`/teams/${home.abbreviation}?tab=news`}><u>All {home.abbreviation} news</u></Link></p>
    </div>
  );
}

export default function News() {
  const { data } = useApi('/teams');
  const [params, setParams] = useSearchParams();
  const team = params.get('team');
  const setTeam = (t) => { const next = new URLSearchParams(params); if (t) next.set('team', t); else next.delete('team'); setParams(next, { replace: true }); };
  return (
    <section>
      <div className="page-head">
        <div><h1>News</h1><p className="muted small">League news in short, sourced summaries — plus stories built from live data.</p></div>
        <label className="week-select">
          <select value={team || ''} onChange={(e) => setTeam(e.target.value)}>
            <option value="">All teams</option>
            {(data?.data || []).map((t) => <option key={t.id} value={t.abbreviation}>{t.name}</option>)}
          </select>
        </label>
      </div>
      <div className="news-layout">
        <div className="news-main"><NewsFeed team={team} /></div>
        <SocialWidget team={team} limit={15} title={team ? `Social · ${team}` : 'Social'} />
      </div>
    </section>
  );
}

export function NewsStory() {
  const { storyId } = useParams();
  const { data, error, loading } = useApi(`/news/${storyId}`);
  if (loading) return <Loading label="Loading story…" />;
  if (error) return <ErrorBox error={error} />;
  const s = data.data;
  return (
    <section className="story">
      <p className="small"><Link to="/news"><u>← News</u></Link></p>
      <div className="story-meta">
        <span className={`story-type ${s.kind}`}>{s.type}</span>
        <span className="muted small">{new Date(s.published).toLocaleString(undefined, { weekday: 'short', month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })}</span>
      </div>
      <h1 className="story-h1">{s.title}</h1>
      <div className="card story-body">
        {s.summary && <p>{s.summary}</p>}
        {(s.body || []).map((p) => <p key={p}>{p}</p>)}
        {s.list?.length > 0 && (
          <ul>
            {s.list.map((x) => <li key={x.text}>{x.player?.id ? <Link to={`/players/${x.player.id}`}><u>{x.text}</u></Link> : x.text}</li>)}
          </ul>
        )}
        {s.game_id && <p><Link to={`/game/${s.game_id}`}><u>Full box score and play-by-play →</u></Link></p>}
        {!s.summary && !s.body?.length && <p className="muted">Summary pending. See the sources below.</p>}
        {s.ai_note && <p className="ai-note">{s.ai_note}</p>}
      </div>

      {(s.teams.length > 0 || s.players.length > 0) && (
        <div className="story-tags">
          {s.teams.map((t) => <Link key={t.abbreviation} to={`/teams/${t.abbreviation}?tab=news`} className="tag team-tag"><Logo src={t.logo} size={16} />{t.name}</Link>)}
          {s.players.map((p) => <Link key={p.id} to={`/players/${p.id}`} className="tag">{p.name}</Link>)}
        </div>
      )}

      <h2 className="section-title">Sources</h2>
      <div className="card list-card">
        {s.sources.map((x) => (
          <a key={x.url} href={x.url} target="_blank" rel="noreferrer" className="news">
            <b>{x.title}</b>
            <div className="muted small">{x.name}{x.published ? ` · ${new Date(x.published).toLocaleDateString()}` : ''}</div>
          </a>
        ))}
      </div>

      {s.related?.length > 0 && (
        <>
          <h2 className="section-title">Related</h2>
          <div className="grid story-grid">{s.related.map((r) => <StoryCard key={r.id} s={r} />)}</div>
        </>
      )}
      {s.ai && <p className="muted small note">AI provider: {s.ai.provider} ({s.ai.model}), {new Date(s.ai.generated_at).toLocaleString()}.</p>}
    </section>
  );
}
